### PR TITLE
fix XPC_ERROR_CONNECTION_INTERRUPTED

### PR DESCRIPTION
**Pull request by erpapa**
```
2019-09-02 15:20:34.248490+0800 ModelViewer[83574:5317178] [DYMTLInitPlatform] platform initialization successful
2019-09-02 15:20:34.349932+0800 ModelViewer[83574:5317099] Metal GPU Frame Capture Enabled
2019-09-02 15:20:34.350451+0800 ModelViewer[83574:5317099] Metal API Validation Enabled
2019-09-02 15:20:34.856238+0800 ModelViewer[83574:5317099] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-09-02 15:20:34.856282+0800 ModelViewer[83574:5317099] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 1 try
2019-09-02 15:20:34.892013+0800 ModelViewer[83574:5317099] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-09-02 15:20:34.892048+0800 ModelViewer[83574:5317099] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 2 try
2019-09-02 15:20:34.931590+0800 ModelViewer[83574:5317099] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-09-02 15:20:34.931626+0800 ModelViewer[83574:5317099] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 3 try
Assertion failed: (error == nil), function -[NuoComputePipeline initWithDevice:withFunction:], file /Users/apple/Documents/Github/NuoModelViewer/ModelViewer/ViewerFoundation/Render/NuoComputeEncoder.mm, line 52.
```

### CODE REVIEW

**Comment by middlefeng** [comment]
@erpapa Which macOS version and GPU have you observed the `XPC_ERROR_CONNECTION_INTERRUPTED` on?

**Comment by erpapa** [comment]
> @erpapa Which macOS version and GPU have you observed the `XPC_ERROR_CONNECTION_INTERRUPTED` on?

Xcode: 10.3 (10G8)
OS: macOS 10.14.6 (18G84)
GPU: Intel Iris Pro 1536 MB

**Comment by middlefeng** [comment]
@erpapa I really appreciate you took time to investigate this and try to make it work on Intel Iris. It would be great if the code base works on Intel Iris since that's the most accessible GPU for Mac users. But this PR alone seems far from solving the problem.

The first thing is that I still reproduce serious rendering problem (the colors are entirely messed up) whenever I rotate the model (which incur a disabling of MSAA mode and then resume).

When I tried to avoid rotating the mode, I still encounter incorrectness in the ray-tracing mode. The translucency overlay of a virtual surface (which is call a board object in the menu) does not work, and the ambient effect is incorrect.

I'm sorry that Intel Iris seems too problematic in its driver to be resolved by a simple fix like this. I would really appreciate if you could follow up with a full fix, which may or may not need support from Apple.

**Comment by erpapa** [comment]
@middlefeng `the colors are entirely messed up`
 I don't understand what do you mean, Can you provide a screenshot?

**Comment by middlefeng** [comment]
@erpapa Sorry for very occupied by many things. The attachment is an example of the color problem. Unfortunately we still have not had any robust solution to make the code work on Intel GPU.

image

**Comment by middlefeng** [comment]
Sorry for having to close this PR without merge. Intel GPU support is still challenging and this project is now prioritizing it below some other features.

**Pull request closed without merging**
